### ISSUE TITLE
Could you update this to version 12?

### ISSUE THREAD

**Issue by michael-jennings** [typewig/bitwig-api-ts-stubs#1]
Or just add a v12 branch?  I just spent 6 hours trying to accomplish this and keep running into snag after snag :'(

**Comment by joslarson** [comment]
@michael-jennings Sorry I just saw this! Ever since I started working at a job that uses Github, all my non work related Github notifications get lost (I need to figure out a better process).

Anyways, I've been working recently on a new version of this with much better types. I haven't had time quite to get it all integrated here, but here's a copy of the resulting type file: https://gist.github.com/joslarson/ffa3b59b5c277f6663124caba3c71aca

**Comment by joslarson** [comment]
@michael-jennings I got an RC up on npm last night, if you want to try it out: https://www.npmjs.com/package/typed-bitwig-api/v/12.0.0-rc.1

**Comment by michael-jennings** [comment]
BROOOO Thank you so much!!!

**Comment by michael-jennings** [comment]
You ROCK

**Comment by IlanFrumer** [comment]
I made my own package if anyone is interested.
This generator can be run locally against your bitwig studio resources
https://github.com/IlanFrumer/BitwigTypesGenerator

**Comment by joslarson** [comment]
> I made my own package if anyone is interested.
> This generator can be run locally against your bitwig studio resources
> https://github.com/IlanFrumer/BitwigTypesGenerator

@IlanFrumer I love seeing someone else taking time to dig into this! I've been through a couple iterations trying to make these more and more correct. I need to publish a release version of the latest because it uses the actual Java AST to generate the types and so it even generates correct types for overloaded methods/functions. Enums are still an issue because some of them can't be access in JS.

**Comment by joslarson** [comment]
v12 is now published: https://www.npmjs.com/package/typed-bitwig-api/v/12.0.0
